# Generated by Django 4.2.3 on 2023-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobaltSystemApp', '0006_remove_add_user_first_name_add_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_user',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
