# Generated by Django 4.2.3 on 2023-07-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobaltSystemApp', '0007_add_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_user',
            name='document',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='add_user',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
