# Generated by Django 4.2.3 on 2023-07-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobaltSystemApp', '0009_remove_add_user_age_remove_add_user_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_user',
            name='name',
        ),
        migrations.AddField(
            model_name='add_user',
            name='fname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
