# Generated by Django 4.2.3 on 2023-07-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobaltSystemApp', '0010_remove_add_user_name_add_user_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_user',
            old_name='fname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='add_user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='add_user',
            name='document',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='add_user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='add_user',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
